spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_database
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never

